# Generated by Django 5.2.6 on 2026-01-02 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the device', max_length=100, unique=True)),
                ('name', models.CharField(help_text="Device name (e.g., 'Living Room Sensor')", max_length=200)),
                ('location', models.CharField(blank=True, help_text='Physical location of the device', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the device is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of the device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
