# Generated by Django 5.2.6 on 2026-01-02 07:22

import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=monitoring.models.generate_device_id, editable=False, help_text='Unique identifier for the device', max_length=100, unique=True),
        ),
    ]
